### ISSUE TITLE
aframe?

### ISSUE THREAD

**Issue by coderofsalvation** [MozillaReality/MOZ_text#1]
Hi.
First of all: awesome.
I had this dream of text embedded in glTF, so I don't have to use big PNG's with text in mozilla hubs-rooms.

..and suddenly I noticed the twitter-post...mind blown.
Does this mean it will be automatically supported by aframe  / mozilla hubs?

**Comment by feiss** [comment]
There's an issue open in spoke about text: https://github.com/mozilla/Spoke/issues/945 so you can expect that hubs/spoke will support text in the near future.

For aframe to support this it should have to use my modified GLTFLoader, which I don't think it will happen, it breaks compatibility with next versions of the loader. But when the GLTFLoader plugin system lands (https://github.com/mrdoob/three.js/pull/19144), that will definitively help things, and the integration with aframe will be much more seamless.
